manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0  # 使用 ZMK v0.3.0
      # 移除 import: true，避免导入 west.yml
  self:
    path: .
