manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.6.0  # 锁定稳定版本
      import: true      # 从 ZMK 导入所有模块（包括板型定义）
  self:
    path: .
