# 1. 设置蓝牙广播名称
CONFIG_ZMK_KEYBOARD_NAME="Nordic_Blinky"

# 2. 开启最高 BLE 发射功率 (+8dBm)，确保信号强度与覆盖范围
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 3. 禁用自动休眠与软关机，保证通电后持续稳定发射信号
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_PM_SOFT_OFF=n

# 4. 禁用无用外设与外接电源输出，精简固件体积并降低不必要的功耗
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_EXT_POWER=n
